# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 149410ea684dc1cc26daa488bc1d473dac87fa676e9ba0bc0ac580255cf0aaf62360ec8a84c0b283181e156e52a4504718c70602ce6888bd19560719ccabf688

test:
  secret_key_base: 2b0ba0796f3e0c24b651f10f958abd5d83bb3ff00f3fd6970d765c2f5bb74195013931f9acde8dced2b1418a0b54eea67c0cb75114c8eff64fc8166440813aa9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
